image_dir: ""
train_json: "train.json"
val_json: "valid.json"
test_json: "test.json"

batch_size: 32
learning_rate: 0.0005
num_epochs: 5
max_seq_length: 64

device: "cuda"

image_size: 224
embedding_dim: 512
fusion_hidden_dim: 256
num_classes: 2  # yes or no

model_save_path: "vqa_model.pth"
