# configs/config.yaml
image_dir: "ecgImages"
train_json: "train.json"
val_json: "valid.json"
test_json: "test.json"

# Training parameters
batch_size: 16
learning_rate: 3e-5
weight_decay: 0.01
num_epochs: 15
max_seq_length: 64
grad_accum_steps: 2
freeze_bert: True

# Model architecture
device: "cuda"
image_size: 512
embedding_dim: 512
fusion_hidden_dim: 512
num_classes: 2
num_attention_heads: 8

# Paths
model_save_path: "clinical_vqa_model.pth"
checkpoint_path: "training_checkpoint.pth"